import { useState, useEffect } from 'react';
import { Container, Row, Col } from 'react-bootstrap';

const MadLibs = () => {

  const [ take, setTake ] = useState('');

  const takeGenerator = () => {
    const playerOrTeam = ['player', 'team'];
    const predictOrDeclare = ['predict', 'declare'];
    const players = ['LeBron James', 'Kawhi Leonard', 'Giannis Antetokounmpo', 'Steph Curry', 'Anthony Davis', 'Luka Doncic', 'Kevin Durant', 'James Harden', 'Damian Lillard', 'Nikola Jokic', 'Devin Booker'];
    const teams = ['Phoenix Suns', 'LA Lakers', 'LA Clippers', 'Denver Nuggets', 'New York Knicks', 'Brooklyn Nets', 'Cleveland Cavaliers', 'Chicago Bulls'];
    const playerDeclareAux = ['is', 'is not'];
    const playerPredictAux = ['will', 'will never'];
    const teamDeclareAux = ['are', 'are not'];
    const teamPredictAux = ['will', 'will never'];
    const playerDeclare = ['a top 10 player', 'terrible at defense', 'going to ask for a trade', 'an all-star caliber player', 'in the same league as Michael and Kobe'];
    const playerPredict = ['win a championship', 'be MVP', 'score 45+ in a game', 'be a complete liability on defense'];
    const teamDeclare = ['a top 5 team', 'in a second-tier market'];
    const teamPredict = ['make the playoffs', 'move cities eventually'];

    let resultTake = '';

    const pickStart = playerOrTeam[Math.floor(Math.random() * 2)];
    const pickDirection = predictOrDeclare[Math.floor(Math.random() * 2)];

    if (pickStart === 'team') {
      resultTake += 'The ' + teams[Math.floor(Math.random() * teams.length)];
      if (pickDirection === 'predict') {
        resultTake += ' ' + teamPredictAux[Math.floor(Math.random() * teamPredictAux.length)];
        resultTake += ' ' + teamPredict[Math.floor(Math.random() * teamPredictAux.length)] + '.';
      }
      if (pickDirection === 'declare') {
        resultTake += ' ' + teamDeclareAux[Math.floor(Math.random() * teamDeclareAux.length)];
        resultTake += ' ' + teamDeclare[Math.floor(Math.random() * teamDeclareAux.length)] + '.';
      }
    }

    if (pickStart === 'player') {
      resultTake += players[Math.floor(Math.random() * teams.length)];
      if (pickDirection === 'predict') {
        resultTake += ' ' + playerPredictAux[Math.floor(Math.random() * playerPredictAux.length)];
        resultTake += ' ' + playerPredict[Math.floor(Math.random() * playerPredictAux.length)] + '.';
      }
      if (pickDirection === 'declare') {
        resultTake += ' ' + playerDeclareAux[Math.floor(Math.random() * playerDeclareAux.length)];
        resultTake += ' ' + playerDeclare[Math.floor(Math.random() * playerDeclareAux.length)] + '.';
      }
    }

    setTake(resultTake);
  }

  useEffect(() => {
    takeGenerator();
  }, []);

  const handleNewTake = (e) => {
    e.preventDefault();
    takeGenerator();
  }

  return (
    <div>
      <div>
        {take}
      </div>
      <div>
        <a className="twitter-share-button"
        href={`https://twitter.com/intent/tweet?text=HOT TAKE: ${take} - Generated by HoopsBot`}
        target="_blank">Genius. Tweet it.</a>
      </div>
      <button onClick={(e) => handleNewTake(e)}>Generate a Take</button>
    </div>
  );
};

export default MadLibs;

// https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview