import React from "react";
import styles from "./Header.module.css";

const Header = () => {
  return (
    <div className={styles.headerRoot}>
      <h1>HoopsBot 🔥</h1>
      <h3>NBA hot takes generated by OpenAI</h3>
    </div>
  );
};

export default Header;
